config/routes.rb
Wdwparks::Application.routes.draw do
  resources :photos

  resources :attractions

  resources :lands

  resources :parks

  match '/auth/:provider/callback', :to => 'sessions#callback'

  root :to => "parks#index"

end

app/models/land.rb
class Land < ActiveRecord::Base
  belongs_to :park
  has_many :attractions

  # Overall method: Get a list, save the list, and then itereate through the list to update the individual lands.
  def self.get_list_of_lands_in_the_current_park_from_touringplans_com(wdwparks_permalink_of_park)
    # returns land names and permalinks 
    require 'nokogiri'
    require 'open-uri'
    
    url = "http://touringplans.com/#{wdwparks_permalink_of_park}/lands"
    puts url
    doc = Nokogiri::HTML(open(url))
    @lands = doc.css(".dv_titleboxtxt a")     
    return @lands
  end
  
  def self.save_current_list_of_lands_from_touringplans_com(wdwparks_permalink_of_park, hash_array_from_touringplans_com)
    # mock this in the test
    # returns the details of the named land
    @park = Park.find_by_permalink(wdwparks_permalink_of_park)
    @lands = hash_array_from_touringplans_com
    @lands.each do |land|
      @land         = Land.find_or_initialize_by_permalink(land.attributes["href"].value)
      @land.name    = land.text
      @land.park    = Park.find_by_permalink(wdwparks_permalink_of_park)
      if @land.save
        puts "Saved:  #{@land.name}, #{@land.permalink}"
      else
        puts "Failed: #{@land.name} -- #{@land.errors}"
      end
    end
  end
  
end

app/controllers/lands_controller.rb
class LandsController < ApplicationController
  # GET /lands
  # GET /lands.xml
  def index
    @lands = Land.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @lands }
    end
  end

  # GET /lands/1
  # GET /lands/1.xml
  def show
    @land = Land.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @land }
    end
  end

  # GET /lands/new
  # GET /lands/new.xml
  def new
    @land = Land.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @land }
    end
  end

  # GET /lands/1/edit
  def edit
    @land = Land.find(params[:id])
  end

  # POST /lands
  # POST /lands.xml
  def create
    @land = Land.new(params[:land])

    respond_to do |format|
      if @land.save
        format.html { redirect_to(@land, :notice => 'Land was successfully created.') }
        format.xml  { render :xml => @land, :status => :created, :location => @land }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @land.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /lands/1
  # PUT /lands/1.xml
  def update
    @land = Land.find(params[:id])

    respond_to do |format|
      if @land.update_attributes(params[:land])
        format.html { redirect_to(@land, :notice => 'Land was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @land.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /lands/1
  # DELETE /lands/1.xml
  def destroy
    @land = Land.find(params[:id])
    @land.destroy

    respond_to do |format|
      format.html { redirect_to(lands_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/lands_helper.rb
module LandsHelper
end

app/views/lands/_form.html.erb
<%= form_for(@land) do |f| %>
  <% if @land.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@land.errors.count, "error") %> prohibited this land from being saved:</h2>

      <ul>
      <% @land.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :park_id %><br />
    <%= f.text_field :park_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lands/edit.html.erb
<h1>Editing land</h1>

<%= render 'form' %>

<%= link_to 'Show', @land %> |
<%= link_to 'Back', lands_path %>

app/views/lands/index.html.erb
<h1>Listing lands</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Park</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @lands.each do |land| %>
  <tr>
    <td><%= land.name %></td>
    <td><%= land.park_id %></td>
    <td><%= link_to 'Show', land %></td>
    <td><%= link_to 'Edit', edit_land_path(land) %></td>
    <td><%= link_to 'Destroy', land, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Land', new_land_path %>

app/views/lands/new.html.erb
<h1>New land</h1>

<%= render 'form' %>

<%= link_to 'Back', lands_path %>

app/views/lands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @land.name %>
</p>

<p>
  <b>Park:</b>
  <%= @land.park_id %>
</p>


<%= link_to 'Edit', edit_land_path(@land) %> |
<%= link_to 'Back', lands_path %>