config/routes.rb
Wdwparks::Application.routes.draw do
  resources :photos

  resources :attractions

  resources :lands

  resources :parks

  match '/auth/:provider/callback', :to => 'sessions#callback'

  root :to => "parks#index"

end

app/models/park.rb
class Park < ActiveRecord::Base
  has_many :lands
  has_many :attractions

  # Overall method: Get a list, save the list, and then itereate through the list to update the individual parks.
  
  def self.get_list_of_parks
    # returns park names and permalinks 
    @parks = [{"name" => "Magic Kingdom", "permalink" =>  "magic-kingdom", "rating" =>  5, "credit" =>  "touringplans.com"},
       {"name" => "Animal Kingdom", "permalink" =>  "animal-kingdom", "rating" =>  3, "credit" =>  "touringplans.com"},
       {"name" => "Epcot", "permalink" =>  "epcot", "rating" =>  4, "credit" =>  "touringplans.com"},
       {"name" => "Disney's Hollywood Studios", "permalink" =>  "hollywood-studios", "rating" =>  3, "credit" =>  "touringplans.com"},
       {"name" => "Blizzard Beach", "permalink" =>  "blizzard-beach", "rating" =>  2, "credit" =>  "touringplans.com"},
       {"name" => "Typhoon Lagoon", "permalink" =>  "typhoon-lagoon", "rating" =>  2, "credit" =>  "touringplans.com"} ]
    return @parks
  end
  
  def self.save_list_of_parks_in_WDW(hash_array_from_get_list_of_parks)
    @parks = hash_array_from_get_list_of_parks
    @parks.each do |park|
      # puts "link:  #{park['permalink']}"
      @park = Park.find_or_initialize_by_permalink(park['permalink'])
      @park.name    = park['name']
      @park.rating  = park['rating']
      @park.credit = park['credit']
      if @park.save
        puts "Saved:  #{@park.name}"
      else
        puts "Failed: #{@park.name} -- #{@park.errors}"
      end
    end
  end
  
  
end

app/controllers/parks_controller.rb
class ParksController < ApplicationController
  # GET /parks
  # GET /parks.xml
  def index
    @parks = Park.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @parks }
    end
  end

  # GET /parks/1
  # GET /parks/1.xml
  def show
    @park = Park.find(params[:id])
    @rides = @park.attractions.where(:category_code  => "ride")
    @shows = @park.attractions.where(:category_code  => "continuous_show")
    

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @park }
    end
  end

  # GET /parks/new
  # GET /parks/new.xml
  def new
    @park = Park.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @park }
    end
  end

  # GET /parks/1/edit
  def edit
    @park = Park.find(params[:id])
  end

  # POST /parks
  # POST /parks.xml
  def create
    @park = Park.new(params[:park])

    respond_to do |format|
      if @park.save
        format.html { redirect_to(@park, :notice => 'Park was successfully created.') }
        format.xml  { render :xml => @park, :status => :created, :location => @park }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @park.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /parks/1
  # PUT /parks/1.xml
  def update
    @park = Park.find(params[:id])

    respond_to do |format|
      if @park.update_attributes(params[:park])
        format.html { redirect_to(@park, :notice => 'Park was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @park.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /parks/1
  # DELETE /parks/1.xml
  def destroy
    @park = Park.find(params[:id])
    @park.destroy

    respond_to do |format|
      format.html { redirect_to(parks_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/parks_helper.rb
module ParksHelper
end

app/views/parks/_form.html.erb
<%= form_for(@park) do |f| %>
  <% if @park.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@park.errors.count, "error") %> prohibited this park from being saved:</h2>

      <ul>
      <% @park.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/parks/edit.html.erb
<h1>Editing park</h1>

<%= render 'form' %>

<%= link_to 'Show', @park %> |
<%= link_to 'Back', parks_path %>

app/views/parks/index.html.erb
<h1>Listing parks</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @parks.each do |park| %>
  <tr>
    <td><%= park.name %></td>
    <td><%= link_to 'Show', park %></td>
    <td><%= link_to 'Edit', edit_park_path(park) %></td>
    <td><%= link_to 'Destroy', park, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Park', new_park_path %>

app/views/parks/new.html.erb
<h1>New park</h1>

<%= render 'form' %>

<%= link_to 'Back', parks_path %>

app/views/parks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @park.name %>
</p>


<%= link_to 'Edit', edit_park_path(@park) %> |
<%= link_to 'Back', parks_path %>