config/routes.rb
Wdwparks::Application.routes.draw do
  resources :photos

  resources :attractions

  resources :lands

  resources :parks

  match '/auth/:provider/callback', :to => 'sessions#callback'

  root :to => "parks#index"

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  include HTTParty
  
  def self.find_photos_on_flickr(photo_search, quantity, photogenic_type)
      # httparty initializer
      format :json
      
      # basic initializers
      my_photo_search = photo_search.gsub(/'/, "\\\\'")
      total_photo_count = 0
      diff_quantity = 0
      @photos = []
      if photogenic_type == 'Attraction'
        @attraction = Attraction.find_by_name(photo_search)
        park_name = @attraction.park.name.gsub(/'/, "\\\\'")
        search_type = 'Attraction'
      else
        park_name = photo_search.gsub(/'/, "\\\\'")
        search_type = 'Park'
      end
      
      
      # search bases
      initial_search = "select * from flickr.photos.search where text ='#{my_photo_search}' and woe_id in (SELECT woeid FROM geo.places WHERE text='lake buena vista, FL' or text='bay lake, FL' or text='Windermere, FL') and api_key='075553032130e8023b265c3259d93c77' limit "
      parent_park_search_pt1 = "select * from flickr.photos.search where text ='"
      parent_park_search_pt2 = "' and woe_id in (SELECT woeid FROM geo.places WHERE text='lake buena vista, FL' or text='bay lake, FL' or text='Windermere, FL') and api_key='075553032130e8023b265c3259d93c77' limit "
      wdw_search = "SELECT * FROM flickr.photos.search WHERE woe_id in (SELECT woeid FROM geo.places WHERE text='lake buena vista, FL' or text='bay lake, FL' or text='Windermere, FL') and api_key='075553032130e8023b265c3259d93c77' limit "
      yql_search = initial_search

      
      # process
      while total_photo_count < quantity do
        diff_quantity = quantity.to_i - total_photo_count.to_i
        yql_search_with_limit = yql_search + diff_quantity.to_s
        puts "=============================="
        puts "search_type is #{search_type}"
        puts "---------"
        puts "yql_search_with_limit"
        puts "#{yql_search_with_limit}"
        puts "---------"
        @yql_results = get("http://query.yahooapis.com/v1/public/yql", 
                :query =>  {:q => yql_search_with_limit, :format =>  'json'})
        photo_count = @yql_results['query']['count']
        # troubleshooting indicators
        logger.debug "results:  #{photo_count.to_i}; quantity:#{quantity.to_i}; total photo count #{total_photo_count.to_i}; diff_quantity #{diff_quantity.to_i}"
        puts "results:  #{photo_count.to_i}; quantity: #{quantity.to_i}; total photo count: #{total_photo_count.to_i}; diff_quantity: #{diff_quantity.to_i}"
        if photo_count > 0 && !photo_search.blank?
          @photo_search_results = @yql_results['query']['results']['photo']
          unless @photo_search_results.kind_of?(Array) 
            @photo_search_results = [@photo_search_results]
          end
          @photos += @photo_search_results
          total_photo_count += photo_count.to_i
          diff_quantity = quantity.to_i - total_photo_count.to_i
        end
        
        # bump up to parent resource
        # Basically there are, at most, three passes: Attraction, Park, and WDW 
        if search_type == 'Attraction'
          # nb: this search needs to be tweaked from searching the park to the specific attraction
          yql_search = parent_park_search_pt1 + park_name + parent_park_search_pt2
          search_type = 'Park'
        elsif search_type == 'Park'
          # nb: current park search needs to be tweaked from searching the park to the specific land
          
          yql_search = parent_park_search_pt1 + park_name + parent_park_search_pt2
          search_type = 'Park'
        else
          # nb: current park search needs to be tweaked from searching WDW to the specific park
          search_type = 'wdw_search'
          yql_search = wdw_search
        end
        
      end
      unless @photos.kind_of?(Array) 
        @photos = [@photos]
      end
      return @photos
  end  
  
  
  belongs_to :photogenic, :polymorphic => true
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  # GET /photos
  # GET /photos.xml
  def index
    @photos = Photo.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @photos }
    end
  end

  # GET /photos/1
  # GET /photos/1.xml
  def show
    @photo = Photo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @photo }
    end
  end

  # GET /photos/new
  # GET /photos/new.xml
  def new
    @photo = Photo.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @photo }
    end
  end

  # GET /photos/1/edit
  def edit
    @photo = Photo.find(params[:id])
  end

  # POST /photos
  # POST /photos.xml
  def create
    @photo = Photo.new(params[:photo])

    respond_to do |format|
      if @photo.save
        format.html { redirect_to(@photo, :notice => 'Photo was successfully created.') }
        format.xml  { render :xml => @photo, :status => :created, :location => @photo }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @photo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /photos/1
  # PUT /photos/1.xml
  def update
    @photo = Photo.find(params[:id])

    respond_to do |format|
      if @photo.update_attributes(params[:photo])
        format.html { redirect_to(@photo, :notice => 'Photo was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @photo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.xml
  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to(photos_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<%= form_for(@photo) do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :farm %><br />
    <%= f.text_field :farm %>
  </div>
  <div class="field">
    <%= f.label :server %><br />
    <%= f.text_field :server %>
  </div>
  <div class="field">
    <%= f.label :secret %><br />
    <%= f.text_field :secret %>
  </div>
  <div class="field">
    <%= f.label :owner %><br />
    <%= f.text_field :owner %>
  </div>
  <div class="field">
    <%= f.label :photogenic_id %><br />
    <%= f.text_field :photogenic_id %>
  </div>
  <div class="field">
    <%= f.label :photogenic_type %><br />
    <%= f.text_field :photogenic_type %>
  </div>
  <div class="field">
    <%= f.label :flickr_id %><br />
    <%= f.text_field :flickr_id %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<h1>Listing photos</h1>

<table>
  <tr>
    <th>Url</th>
    <th>Farm</th>
    <th>Server</th>
    <th>Secret</th>
    <th>Owner</th>
    <th>Photogenic</th>
    <th>Photogenic type</th>
    <th>Flickr</th>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @photos.each do |photo| %>
  <tr>
    <td><%= photo.url %></td>
    <td><%= photo.farm %></td>
    <td><%= photo.server %></td>
    <td><%= photo.secret %></td>
    <td><%= photo.owner %></td>
    <td><%= photo.photogenic_id %></td>
    <td><%= photo.photogenic_type %></td>
    <td><%= photo.flickr_id %></td>
    <td><%= photo.title %></td>
    <td><%= link_to 'Show', photo %></td>
    <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
    <td><%= link_to 'Destroy', photo, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Photo', new_photo_path %>

app/views/photos/new.html.erb
<h1>New photo</h1>

<%= render 'form' %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Url:</b>
  <%= @photo.url %>
</p>

<p>
  <b>Farm:</b>
  <%= @photo.farm %>
</p>

<p>
  <b>Server:</b>
  <%= @photo.server %>
</p>

<p>
  <b>Secret:</b>
  <%= @photo.secret %>
</p>

<p>
  <b>Owner:</b>
  <%= @photo.owner %>
</p>

<p>
  <b>Photogenic:</b>
  <%= @photo.photogenic_id %>
</p>

<p>
  <b>Photogenic type:</b>
  <%= @photo.photogenic_type %>
</p>

<p>
  <b>Flickr:</b>
  <%= @photo.flickr_id %>
</p>

<p>
  <b>Title:</b>
  <%= @photo.title %>
</p>


<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>