config/routes.rb
Wdwparks::Application.routes.draw do
  resources :photos

  resources :attractions

  resources :lands

  resources :parks

  match '/auth/:provider/callback', :to => 'sessions#callback'

  root :to => "parks#index"

end

app/controllers/attractions_controller.rb
class AttractionsController < ApplicationController
  # GET /attractions
  # GET /attractions.xml
  def index
    @attractions = Attraction.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @attractions }
    end
  end

  # GET /attractions/1
  # GET /attractions/1.xml
  def show
    @attraction = Attraction.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @attraction }
    end
  end

  # GET /attractions/new
  # GET /attractions/new.xml
  def new
    @attraction = Attraction.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @attraction }
    end
  end

  # GET /attractions/1/edit
  def edit
    @attraction = Attraction.find(params[:id])
  end

  # POST /attractions
  # POST /attractions.xml
  def create
    @attraction = Attraction.new(params[:attraction])

    respond_to do |format|
      if @attraction.save
        format.html { redirect_to(@attraction, :notice => 'Attraction was successfully created.') }
        format.xml  { render :xml => @attraction, :status => :created, :location => @attraction }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @attraction.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /attractions/1
  # PUT /attractions/1.xml
  def update
    @attraction = Attraction.find(params[:id])

    respond_to do |format|
      if @attraction.update_attributes(params[:attraction])
        format.html { redirect_to(@attraction, :notice => 'Attraction was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @attraction.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /attractions/1
  # DELETE /attractions/1.xml
  def destroy
    @attraction = Attraction.find(params[:id])
    @attraction.destroy

    respond_to do |format|
      format.html { redirect_to(attractions_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/attractions_helper.rb
module AttractionsHelper
end

app/views/attractions/_form.html.erb
<%= form_for(@attraction) do |f| %>
  <% if @attraction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attraction.errors.count, "error") %> prohibited this attraction from being saved:</h2>

      <ul>
      <% @attraction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :permalink %><br />
    <%= f.text_field :permalink %>
  </div>
  <div class="field">
    <%= f.label :short_name %><br />
    <%= f.text_field :short_name %>
  </div>
  <div class="field">
    <%= f.label :when_to_go %><br />
    <%= f.text_field :when_to_go %>
  </div>
  <div class="field">
    <%= f.label :scheduled_code %><br />
    <%= f.text_field :scheduled_code %>
  </div>
  <div class="field">
    <%= f.label :reflective_captioning %><br />
    <%= f.text_field :reflective_captioning %>
  </div>
  <div class="field">
    <%= f.label :physical_considerations %><br />
    <%= f.text_field :physical_considerations %>
  </div>
  <div class="field">
    <%= f.label :open_not_so_scary %><br />
    <%= f.text_field :open_not_so_scary %>
  </div>
  <div class="field">
    <%= f.label :open_emh_evening %><br />
    <%= f.text_field :open_emh_evening %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :duration %><br />
    <%= f.text_field :duration %>
  </div>
  <div class="field">
    <%= f.label :average_wait_assumes %><br />
    <%= f.text_field :average_wait_assumes %>
  </div>
  <div class="field">
    <%= f.label :scope_and_scale_code %><br />
    <%= f.text_field :scope_and_scale_code %>
  </div>
  <div class="field">
    <%= f.label :minor_attraction %><br />
    <%= f.text_field :minor_attraction %>
  </div>
  <div class="field">
    <%= f.label :intense %><br />
    <%= f.text_field :intense %>
  </div>
  <div class="field">
    <%= f.label :video_captioning %><br />
    <%= f.text_field :video_captioning %>
  </div>
  <div class="field">
    <%= f.label :open_very_merry %><br />
    <%= f.text_field :open_very_merry %>
  </div>
  <div class="field">
    <%= f.label :not_to_be_missed %><br />
    <%= f.text_field :not_to_be_missed %>
  </div>
  <div class="field">
    <%= f.label :assistive_listening %><br />
    <%= f.text_field :assistive_listening %>
  </div>
  <div class="field">
    <%= f.label :wheelchair_transfer_code %><br />
    <%= f.text_field :wheelchair_transfer_code %>
  </div>
  <div class="field">
    <%= f.label :must_transfer_from_wheelchair %><br />
    <%= f.text_field :must_transfer_from_wheelchair %>
  </div>
  <div class="field">
    <%= f.label :special_needs %><br />
    <%= f.text_field :special_needs %>
  </div>
  <div class="field">
    <%= f.label :single_rider %><br />
    <%= f.text_field :single_rider %>
  </div>
  <div class="field">
    <%= f.label :seasonal %><br />
    <%= f.text_field :seasonal %>
  </div>
  <div class="field">
    <%= f.label :handheld_captioning %><br />
    <%= f.text_field :handheld_captioning %>
  </div>
  <div class="field">
    <%= f.label :frightening %><br />
    <%= f.text_field :frightening %>
  </div>
  <div class="field">
    <%= f.label :no_service_animals %><br />
    <%= f.text_field :no_service_animals %>
  </div>
  <div class="field">
    <%= f.label :loading_speed %><br />
    <%= f.text_field :loading_speed %>
  </div>
  <div class="field">
    <%= f.label :fastpass_booth %><br />
    <%= f.text_field :fastpass_booth %>
  </div>
  <div class="field">
    <%= f.label :what_it_is %><br />
    <%= f.text_field :what_it_is %>
  </div>
  <div class="field">
    <%= f.label :ultimate_code %><br />
    <%= f.text_field :ultimate_code %>
  </div>
  <div class="field">
    <%= f.label :open_emh_morning %><br />
    <%= f.text_field :open_emh_morning %>
  </div>
  <div class="field">
    <%= f.label :category_code %><br />
    <%= f.text_field :category_code %>
  </div>
  <div class="field">
    <%= f.label :sign_language %><br />
    <%= f.text_field :sign_language %>
  </div>
  <div class="field">
    <%= f.label :service_animal_check %><br />
    <%= f.text_field :service_animal_check %>
  </div>
  <div class="field">
    <%= f.label :rider_swap %><br />
    <%= f.text_field :rider_swap %>
  </div>
  <div class="field">
    <%= f.label :average_wait_per_hundred %><br />
    <%= f.text_field :average_wait_per_hundred %>
  </div>
  <div class="field">
    <%= f.label :probable_wait_time %><br />
    <%= f.text_field :probable_wait_time %>
  </div>
  <div class="field">
    <%= f.label :ultimate_task %><br />
    <%= f.text_field :ultimate_task %>
  </div>
  <div class="field">
    <%= f.label :time_zone %><br />
    <%= f.text_field :time_zone %>
  </div>
  <div class="field">
    <%= f.label :audio_description %><br />
    <%= f.text_field :audio_description %>
  </div>
  <div class="field">
    <%= f.label :height_restriction %><br />
    <%= f.text_field :height_restriction %>
  </div>
  <div class="field">
    <%= f.label :extinct_on %><br />
    <%= f.date_select :extinct_on %>
  </div>
  <div class="field">
    <%= f.label :opened_on %><br />
    <%= f.date_select :opened_on %>
  </div>
  <div class="field">
    <%= f.label :land_id %><br />
    <%= f.text_field :land_id %>
  </div>
  <div class="field">
    <%= f.label :park_id %><br />
    <%= f.text_field :park_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/attractions/edit.html.erb
<h1>Editing attraction</h1>

<%= render 'form' %>

<%= link_to 'Show', @attraction %> |
<%= link_to 'Back', attractions_path %>

app/views/attractions/index.html.erb
<h1>Listing attractions</h1>

<table>
  <tr>
    <th>Permalink</th>
    <th>Short name</th>
    <th>When to go</th>
    <th>Scheduled code</th>
    <th>Reflective captioning</th>
    <th>Physical considerations</th>
    <th>Open not so scary</th>
    <th>Open emh evening</th>
    <th>Name</th>
    <th>Duration</th>
    <th>Average wait assumes</th>
    <th>Scope and scale code</th>
    <th>Minor attraction</th>
    <th>Intense</th>
    <th>Video captioning</th>
    <th>Open very merry</th>
    <th>Not to be missed</th>
    <th>Assistive listening</th>
    <th>Wheelchair transfer code</th>
    <th>Must transfer from wheelchair</th>
    <th>Special needs</th>
    <th>Single rider</th>
    <th>Seasonal</th>
    <th>Handheld captioning</th>
    <th>Frightening</th>
    <th>No service animals</th>
    <th>Loading speed</th>
    <th>Fastpass booth</th>
    <th>What it is</th>
    <th>Ultimate code</th>
    <th>Open emh morning</th>
    <th>Category code</th>
    <th>Sign language</th>
    <th>Service animal check</th>
    <th>Rider swap</th>
    <th>Average wait per hundred</th>
    <th>Probable wait time</th>
    <th>Ultimate task</th>
    <th>Time zone</th>
    <th>Audio description</th>
    <th>Height restriction</th>
    <th>Extinct on</th>
    <th>Opened on</th>
    <th>Land</th>
    <th>Park</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @attractions.each do |attraction| %>
  <tr>
    <td><%= attraction.permalink %></td>
    <td><%= attraction.short_name %></td>
    <td><%= attraction.when_to_go %></td>
    <td><%= attraction.scheduled_code %></td>
    <td><%= attraction.reflective_captioning %></td>
    <td><%= attraction.physical_considerations %></td>
    <td><%= attraction.open_not_so_scary %></td>
    <td><%= attraction.open_emh_evening %></td>
    <td><%= attraction.name %></td>
    <td><%= attraction.duration %></td>
    <td><%= attraction.average_wait_assumes %></td>
    <td><%= attraction.scope_and_scale_code %></td>
    <td><%= attraction.minor_attraction %></td>
    <td><%= attraction.intense %></td>
    <td><%= attraction.video_captioning %></td>
    <td><%= attraction.open_very_merry %></td>
    <td><%= attraction.not_to_be_missed %></td>
    <td><%= attraction.assistive_listening %></td>
    <td><%= attraction.wheelchair_transfer_code %></td>
    <td><%= attraction.must_transfer_from_wheelchair %></td>
    <td><%= attraction.special_needs %></td>
    <td><%= attraction.single_rider %></td>
    <td><%= attraction.seasonal %></td>
    <td><%= attraction.handheld_captioning %></td>
    <td><%= attraction.frightening %></td>
    <td><%= attraction.no_service_animals %></td>
    <td><%= attraction.loading_speed %></td>
    <td><%= attraction.fastpass_booth %></td>
    <td><%= attraction.what_it_is %></td>
    <td><%= attraction.ultimate_code %></td>
    <td><%= attraction.open_emh_morning %></td>
    <td><%= attraction.category_code %></td>
    <td><%= attraction.sign_language %></td>
    <td><%= attraction.service_animal_check %></td>
    <td><%= attraction.rider_swap %></td>
    <td><%= attraction.average_wait_per_hundred %></td>
    <td><%= attraction.probable_wait_time %></td>
    <td><%= attraction.ultimate_task %></td>
    <td><%= attraction.time_zone %></td>
    <td><%= attraction.audio_description %></td>
    <td><%= attraction.height_restriction %></td>
    <td><%= attraction.extinct_on %></td>
    <td><%= attraction.opened_on %></td>
    <td><%= attraction.land_id %></td>
    <td><%= attraction.park_id %></td>
    <td><%= link_to 'Show', attraction %></td>
    <td><%= link_to 'Edit', edit_attraction_path(attraction) %></td>
    <td><%= link_to 'Destroy', attraction, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Attraction', new_attraction_path %>

app/views/attractions/new.html.erb
<h1>New attraction</h1>

<%= render 'form' %>

<%= link_to 'Back', attractions_path %>

app/views/attractions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Permalink:</b>
  <%= @attraction.permalink %>
</p>

<p>
  <b>Short name:</b>
  <%= @attraction.short_name %>
</p>

<p>
  <b>When to go:</b>
  <%= @attraction.when_to_go %>
</p>

<p>
  <b>Scheduled code:</b>
  <%= @attraction.scheduled_code %>
</p>

<p>
  <b>Reflective captioning:</b>
  <%= @attraction.reflective_captioning %>
</p>

<p>
  <b>Physical considerations:</b>
  <%= @attraction.physical_considerations %>
</p>

<p>
  <b>Open not so scary:</b>
  <%= @attraction.open_not_so_scary %>
</p>

<p>
  <b>Open emh evening:</b>
  <%= @attraction.open_emh_evening %>
</p>

<p>
  <b>Name:</b>
  <%= @attraction.name %>
</p>

<p>
  <b>Duration:</b>
  <%= @attraction.duration %>
</p>

<p>
  <b>Average wait assumes:</b>
  <%= @attraction.average_wait_assumes %>
</p>

<p>
  <b>Scope and scale code:</b>
  <%= @attraction.scope_and_scale_code %>
</p>

<p>
  <b>Minor attraction:</b>
  <%= @attraction.minor_attraction %>
</p>

<p>
  <b>Intense:</b>
  <%= @attraction.intense %>
</p>

<p>
  <b>Video captioning:</b>
  <%= @attraction.video_captioning %>
</p>

<p>
  <b>Open very merry:</b>
  <%= @attraction.open_very_merry %>
</p>

<p>
  <b>Not to be missed:</b>
  <%= @attraction.not_to_be_missed %>
</p>

<p>
  <b>Assistive listening:</b>
  <%= @attraction.assistive_listening %>
</p>

<p>
  <b>Wheelchair transfer code:</b>
  <%= @attraction.wheelchair_transfer_code %>
</p>

<p>
  <b>Must transfer from wheelchair:</b>
  <%= @attraction.must_transfer_from_wheelchair %>
</p>

<p>
  <b>Special needs:</b>
  <%= @attraction.special_needs %>
</p>

<p>
  <b>Single rider:</b>
  <%= @attraction.single_rider %>
</p>

<p>
  <b>Seasonal:</b>
  <%= @attraction.seasonal %>
</p>

<p>
  <b>Handheld captioning:</b>
  <%= @attraction.handheld_captioning %>
</p>

<p>
  <b>Frightening:</b>
  <%= @attraction.frightening %>
</p>

<p>
  <b>No service animals:</b>
  <%= @attraction.no_service_animals %>
</p>

<p>
  <b>Loading speed:</b>
  <%= @attraction.loading_speed %>
</p>

<p>
  <b>Fastpass booth:</b>
  <%= @attraction.fastpass_booth %>
</p>

<p>
  <b>What it is:</b>
  <%= @attraction.what_it_is %>
</p>

<p>
  <b>Ultimate code:</b>
  <%= @attraction.ultimate_code %>
</p>

<p>
  <b>Open emh morning:</b>
  <%= @attraction.open_emh_morning %>
</p>

<p>
  <b>Category code:</b>
  <%= @attraction.category_code %>
</p>

<p>
  <b>Sign language:</b>
  <%= @attraction.sign_language %>
</p>

<p>
  <b>Service animal check:</b>
  <%= @attraction.service_animal_check %>
</p>

<p>
  <b>Rider swap:</b>
  <%= @attraction.rider_swap %>
</p>

<p>
  <b>Average wait per hundred:</b>
  <%= @attraction.average_wait_per_hundred %>
</p>

<p>
  <b>Probable wait time:</b>
  <%= @attraction.probable_wait_time %>
</p>

<p>
  <b>Ultimate task:</b>
  <%= @attraction.ultimate_task %>
</p>

<p>
  <b>Time zone:</b>
  <%= @attraction.time_zone %>
</p>

<p>
  <b>Audio description:</b>
  <%= @attraction.audio_description %>
</p>

<p>
  <b>Height restriction:</b>
  <%= @attraction.height_restriction %>
</p>

<p>
  <b>Extinct on:</b>
  <%= @attraction.extinct_on %>
</p>

<p>
  <b>Opened on:</b>
  <%= @attraction.opened_on %>
</p>

<p>
  <b>Land:</b>
  <%= @attraction.land_id %>
</p>

<p>
  <b>Park:</b>
  <%= @attraction.park_id %>
</p>


<%= link_to 'Edit', edit_attraction_path(@attraction) %> |
<%= link_to 'Back', attractions_path %>